# Generated by Django 4.2.5 on 2023-09-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=150, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("difficulty", models.IntegerField()),
                ("solution", models.IntegerField()),
                ("categories", models.ManyToManyField(to="codeforces_data.category")),
            ],
        ),
    ]
